spring:
  application:
    name: ReviewService

  config:
    import: configserver:http://${CONFIG_SERVER_URL:localhost:8082}
  datasource:
    url: jdbc:mysql://${DB_URL:localhost:3306}/petshop
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver

server:
  port: 8087
